# Play Console manual checklist
$ErrorActionPreference = "Continue"

Write-Host ""
Write-Host "=== TalkCash Play Console Checklist (Global) ===" -ForegroundColor Cyan
Write-Host ""
Write-Host "[ ] 1. Create app: TalkCash / io.talkcash.app / Finance"
Write-Host "[ ] 2. Store listing TR+EN (docs/PLAY_STORE_LISTING.md)"
Write-Host "[ ] 3. Privacy: https://talkcash-api-prod.onrender.com/privacy"
Write-Host "[ ] 4. Data safety (docs/GOOGLE_PLAY_DATA_SAFETY.md)"
Write-Host "[ ] 5. Content rating + Financial features (personal finance, NOT broker)"
Write-Host "[ ] 6. Subscriptions — 6 SKU (monthly + yearly):"
Write-Host "       talkcash_pro_monthly / talkcash_pro_yearly"
Write-Host "       talkcash_family_monthly / talkcash_family_yearly"
Write-Host "       talkcash_business_monthly / talkcash_business_yearly"
Write-Host "[ ] 7. Prices tax-inclusive — see mobile/store/regional-pricing.json"
Write-Host "       Pro: US `$8.99/mo `$79.99/yr | TR ₺89,99/mo ₺749,99/yr"
Write-Host "       Family: US `$14.99/mo | TR ₺149,99/mo"
Write-Host "[ ] 8. Countries: 30-wave (docs/PLAY_STORE_REGIONS.md) — IN, US, ID, PK, BR, TR..."
Write-Host "[ ] 9. CN/RU: Play disi — AppGallery/RuStore gelecek (fiyat referansi JSON'da)"
Write-Host "[ ] 10. 7-day trial + intro (US `$4.99 / TR ₺39,99 first month)"
Write-Host "[ ] 11. License testers"
Write-Host "[ ] 12. Internal testing -> AAB #19+"
Write-Host "[ ] 13. Screenshots + feature graphic 1024x500"
Write-Host ""
Write-Host "Pricing docs: docs/PRICING.md"
Write-Host "AAB: https://expo.dev/artifacts/eas/y2kXlEt3uNT7rqgtqwKnCGZojmNK2rZUtRQ_qyrywik.aab"
Write-Host ""
