# TalkCash - Koyeb deploy (Render/Fly alternatifi, ucretsiz tier)
# https://www.koyeb.com -> GitHub ile kayit
#
# Usage: .\scripts\setup-koyeb-prod.ps1

Write-Host ""
Write-Host "TalkCash Backend - Koyeb (Render yoksa)"
Write-Host "========================================"
Write-Host ""
Write-Host "Koyeb ucretsiz tier: 512MB RAM, GitHub deploy, kart cogu zaman gerekmez."
Write-Host ""
Write-Host "ADIM 1: Neon PostgreSQL (ucretsiz)"
Write-Host "  https://console.neon.tech"
Write-Host "  DATABASE_URL:"
Write-Host "  postgresql+asyncpg://user:pass@ep-xxx.neon.tech/neondb?sslmode=require"
Write-Host ""
Write-Host "ADIM 2: Upstash Redis (ucretsiz)"
Write-Host "  https://console.upstash.com -> eu-central-1"
Write-Host ""
Write-Host "ADIM 3: Koyeb"
Write-Host "  1. https://app.koyeb.com -> Sign up with GitHub"
Write-Host "  2. Create App -> GitHub -> eduai-sale repo"
Write-Host "  3. Builder: Dockerfile"
Write-Host "  4. Dockerfile path: backend/Dockerfile"
Write-Host "  5. Work directory: backend"
Write-Host "  6. Port: 8000"
Write-Host "  7. Region: Frankfurt (fra)"
Write-Host "  8. Instance: Free (Nano)"
Write-Host "  9. Environment variables:"
Write-Host "       DATABASE_URL = (Neon)"
Write-Host "       REDIS_URL = (Upstash)"
Write-Host "       SECRET_KEY = (asagidaki)"
Write-Host "       ALLOWED_ORIGINS = *"
Write-Host "       SCHEDULER_ENABLED = true"
Write-Host "       DEBUG = false"
Write-Host "       S3_ENABLED = false"
Write-Host "       OPENAI_API_KEY = sk-... (opsiyonel)"
Write-Host " 10. Deploy -> URL: https://YOUR-APP.koyeb.app"
Write-Host ""
Write-Host "ADIM 4: Mobil"
Write-Host "  EXPO_PUBLIC_API_URL=https://YOUR-APP.koyeb.app/api/v1"
Write-Host "  cd mobile && npx eas-cli build --profile production --platform android"
Write-Host ""

$secretKey = -join ((1..32) | ForEach-Object { "{0:x2}" -f (Get-Random -Maximum 256) })
Write-Host "SECRET_KEY:"
Write-Host $secretKey
Write-Host ""
Write-Host "--- VEYA Render icin (2 dk kayit) ---"
Write-Host "  https://dashboard.render.com -> Sign up with GitHub"
Write-Host "  New -> Blueprint -> repo bagla -> render.yaml"
Write-Host ""
